-- Execute este comando no SQL Editor do seu painel do Supabase
-- Ele vai adicionar todas as novas colunas à tabela "females" existente

ALTER TABLE females 
ADD COLUMN IF NOT EXISTS reg_id text,
ADD COLUMN IF NOT EXISTS tpi numeric,
ADD COLUMN IF NOT EXISTS cheese_merit numeric,
ADD COLUMN IF NOT EXISTS fluid_merit numeric,
ADD COLUMN IF NOT EXISTS fat_pct numeric,
ADD COLUMN IF NOT EXISTS protein_pct numeric,
ADD COLUMN IF NOT EXISTS feed_efficiency numeric,
ADD COLUMN IF NOT EXISTS hcr numeric,
ADD COLUMN IF NOT EXISTS ccr numeric,
ADD COLUMN IF NOT EXISTS early_first_calving numeric,
ADD COLUMN IF NOT EXISTS health_index numeric,
ADD COLUMN IF NOT EXISTS mastitis numeric,
ADD COLUMN IF NOT EXISTS livability numeric,
ADD COLUMN IF NOT EXISTS heifer_livability numeric,
ADD COLUMN IF NOT EXISTS sire_calving_ease numeric,
ADD COLUMN IF NOT EXISTS daughter_calving_ease numeric,
ADD COLUMN IF NOT EXISTS sire_stillbirth numeric,
ADD COLUMN IF NOT EXISTS daughter_stillbirth numeric,
ADD COLUMN IF NOT EXISTS ptat numeric,
ADD COLUMN IF NOT EXISTS bde numeric,
ADD COLUMN IF NOT EXISTS dfm numeric,
ADD COLUMN IF NOT EXISTS sta numeric,
ADD COLUMN IF NOT EXISTS str_val numeric,
ADD COLUMN IF NOT EXISTS fls numeric,
ADD COLUMN IF NOT EXISTS fta numeric,
ADD COLUMN IF NOT EXISTS ftp numeric,
ADD COLUMN IF NOT EXISTS fua numeric,
ADD COLUMN IF NOT EXISTS rlr numeric,
ADD COLUMN IF NOT EXISTS rls numeric,
ADD COLUMN IF NOT EXISTS rpa numeric,
ADD COLUMN IF NOT EXISTS rtp numeric,
ADD COLUMN IF NOT EXISTS ruh numeric,
ADD COLUMN IF NOT EXISTS ruw numeric,
ADD COLUMN IF NOT EXISTS tlg numeric,
ADD COLUMN IF NOT EXISTS trw numeric,
ADD COLUMN IF NOT EXISTS ucl numeric,
ADD COLUMN IF NOT EXISTS udp numeric,
ADD COLUMN IF NOT EXISTS sire_name text,
ADD COLUMN IF NOT EXISTS sire_reg text,
ADD COLUMN IF NOT EXISTS mgs_name text,
ADD COLUMN IF NOT EXISTS dam_reg text,
ADD COLUMN IF NOT EXISTS dam_animal_id text,
ADD COLUMN IF NOT EXISTS beta_casein text,
ADD COLUMN IF NOT EXISTS kappa_casein text;
