/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Existing app colors
        'blue-dark': '#1B3A5C',
        'blue-mid': '#2E6DA4',
        gold: '#C9A84C',
        'green-farm': '#1E7E34',
        'red-farm': '#C0392B',
        'orange-farm': '#E67E22',

        // Landing page colors from user config
        "on-error-container": "#93000a",
        "surface": "#f8f9fb",
        "surface-container": "#edeef0",
        "tertiary": "#755b00",
        "primary-container": "#1b3a5c",
        "inverse-surface": "#2e3132",
        "secondary-fixed": "#d0e4ff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-dim": "#d9dadc",
        "inverse-primary": "#abc9f2",
        "secondary-fixed-dim": "#9bcbff",
        "on-surface": "#191c1e",
        "secondary-container": "#8ac3ff",
        "surface-container-highest": "#e1e2e4",
        "outline": "#73777f",
        "on-primary-fixed-variant": "#2b486b",
        "surface-variant": "#e1e2e4",
        "background": "#f8f9fb",
        "outline-variant": "#c3c6cf",
        "on-tertiary-container": "#503d00",
        "on-surface-variant": "#43474e",
        "surface-tint": "#436084",
        "on-primary-container": "#87a4cc",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#005084",
        "primary-fixed-dim": "#abc9f2",
        "secondary": "#1f6298",
        "tertiary-fixed": "#ffe08f",
        "on-primary-fixed": "#001c38",
        "surface-bright": "#f8f9fb",
        "tertiary-fixed-dim": "#e6c364",
        "surface-container-low": "#f3f4f6",
        "primary-fixed": "#d2e4ff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#c9a84c",
        "on-secondary-fixed-variant": "#004a7a",
        "surface-container-high": "#e7e8ea",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#584400",
        "on-background": "#191c1e",
        "primary": "#002444",
        "inverse-on-surface": "#f0f1f3",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001d34"
      },
      spacing: {
        "margin-desktop": "40px",
        "lg": "48px",
        "base": "8px",
        "margin-mobile": "16px",
        "xl": "80px",
        "md": "24px",
        "gutter": "24px",
        "sm": "12px",
        "xs": "4px"
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "mono-data": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "mono-data": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
};

